Document requirement to pull submodules
Naively following the contribution guide can lead to an error (see below) when running `bun setup` due to the sub-module `src/bun.js/WebKit` not being pulled locally.
 
```
fatal: Unable to find current revision in submodule path 'src/bun.js/WebKit'
error: script "setup" exited with code 128
```